variables:
  JULIA_PKGDIR: "$CI_PROJECT_DIR/.julia/"
  package: 'CUDAapi'

test:0.6:
  image: juliagpu/julia:v0.6-opengl
  before_script:
    - apt-get -qq update
    - apt-get install -y mesa-utils

  script:
    - whoami
    - env
    - export DISPLAY=:0
    - ls /tmp/.X11-unix
    - glxinfo
